# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  issue-title:
    description: 'The title of the issue.'
    required: true
  issue-body:
    description: "The body of the issue."
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}